#!/bin/bash
set -e

./linux_repos.sh
./dev.sh
./python.sh
./haskell.sh
./ocaml.sh
./coq.sh
./node.sh
./toolbox.sh

./docker.sh
./virtualization.sh
# If needed
./databases.sh
./latex.sh
./apps.sh
./battery.sh

./packages.sh

# Thinkpad only
# ./thinkpad.sh

./next_steps.sh
