
import:
 - ~/.config/alacritty/themes/themes/gruvbox_dark.yaml

font:
  normal:
    family: "IosevkaNerdFont"
    style: "Regular"
  size: 16.0

key_bindings:
  - { key: V, mods: Control|Alt, action: Paste }
  - { key: C, mods: Control|Alt, action: Copy }
