#!/usr/bin/env bash

set -e

BIN_FILES_LOCATION=/usr/local/bin
CONFIG="install.conf.yaml"
DOTBOT_DIR="tools/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

sudo cp scripts/* $BIN_FILES_LOCATION
sudo chown -R root:root $BIN_FILES_LOCATION
