#!/bin/bash
# Make sure hard-drive is mounted where we expect it to be. You
# may want to change sdb1 to your backup disk label
sudo umount /dev/sdb1
sudo mount /dev/sdb1 /media/backup

LOCATION="/media/backup/HOME_BACKUP_FEDORA_THINKPAD_1"

sudo mkdir -p $LOCATION
# -a archive mode (enables recursion)
# -A preserve ACLs (access control list)
# -X preserve extended attributes
# -v verbose mode
# --delete synchronize disks 1:1
sudo rsync -aAv \
    --exclude="*/Films" \
    --exclude="*/Programs" \
    --exclude="*/node_modules" \
    --exclude="*/HDD" \
    --exclude="*/HOME_BACKUP" \
    --exclude="*/Anaconda3*" \
    --exclude="*/.PyCharm*" \
    --exclude="*/.cabal" \
    --exclude="*/.cache" \
    --exclude="*/.config" \
    --exclude="*/.esmtp_queue" \
    --exclude="*/.local" \
    --exclude="*/.npm" \
    --exclude="*/.yarn" \
    --exclude="*/.opam" \
    --exclude="*/.vagrant.d" \
    --exclude="*/.pyenv" \
    --exclude="*/.vscode" \
    --exclude="*/.rustup" \
    --exclude="*/.stack" \
    --exclude="*/.virtualenvs" \
    --exclude="*/.thumbnails" \
    --exclude="*/.vols" \
    --exclude="*/.git" \
    --exclude="*/.minecraft" \
    --exclude="*/.mypy_cache" \
    --exclude="*/*tiles*" \
    --exclude="*/*roads*" \
    --exclude="*/*roads*" \
    --exclude="*/VirtualBox VMs" \
    --exclude="*/VirtualMachines" \
    --exclude="*/snap" \
    --exclude="*/anaconda3" \
    --exclude="*/viddddd" \
    --exclude="*/Visual_Paradigm_CE_15.2" \
    --exclude="*.log" \
    --exclude="*/QED/scratchpad" \
    /home/mu $LOCATION

    # --exclude='/**/.*/' \
