#!/bin/bash
LOCATION=$1

set -e

usage="Decrypts all gpgs in given directory

Usage:
    decrypt_gpgs <path>

Options:
    -h, --help    Show this help text
    --dry-run     Display commands to execute and exit"

if [ "$2" == "--dry-run" ]; then
    CMD=echo
else
    CMD="sh -c"
fi

if [ "$#" -lt 1 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "$usage"
  exit 0;
else
    ls -1 $LOCATION \
        | grep "\.gpg$" \
        | awk '{ split($0, a, ".gpg"); print a[1]}' \
        | xargs -I % $CMD "gpg -o $LOCATION/% --decrypt $LOCATION/%.gpg"
fi
